### ISSUE TITLE
Question: Hosting build files

### ISSUE THREAD

**Issue by evamaxfield** [nathandpeterson/cdp-frontend#17]
Hello @nathandpeterson and @trungvngo

Apparently my Slack account was already deactivated but I wanted to move the excellent work you two had done over to the organization for hosting. The actual move over is done:
https://github.com/CouncilDataProject/seattle

But I have a rookie question: I noticed that by default the `build` directory is in the `gitignore`, should I have one repo for "website development" (basically this repo as is) and then a repo for each city that is simply the build for that city? Or can I just remove the ignore marker on the `build` directory and have all files for each city available?

**Comment by nathandpeterson** [comment]
@JacksonMaxfield You shouldn't have to commit the build directory. There are a lot of different ways to build and deploy the app. My first inclination is usually to set up some kind of CICD to take a build artifact and deploy it. If you don't feel like investing the time to set up TravisCI or something through github actions, it looks like github has [this dev-tool](https://github.com/gitname/react-gh-pages) that streamlines manual deployments using github for hosting. I'm glad to continue to work with you through deployment and, at least for awhile, to help address other issues that might crop up client side. I had been hoping to write up a readme during the explorathon but it kind of fell out of scope. Let's keep in touch and I'll be glad to continue to help out as I find time.

**Comment by evamaxfield** [comment]
Ahhh of course! I will try to follow either the dev tool or using the fancy new [GitHub Actions](https://medium.com/@mannyyang/how-to-deploy-a-react-app-to-github-pages-with-github-actions-efd430632a45).

No worries about the README I understand we were all in a hectic mad rush to finish stuff up (as hackathons normally are :smile:). Yes please! I was digging through the code and I understand a lot of it (I think). But really, thank you for all the help already!
